-- Match Scorekeeper backend — initial schema
--
-- Apply with:
--   wrangler d1 migrations apply match-scorekeeper --local
--
-- STAGE NOTE: payloads are stored as plain JSON text for now. Client-side
-- encryption is planned as a later stage. When it lands, `payload` holds
-- base64 ciphertext instead of JSON and an `iv` column is added; nothing else
-- in this schema changes, because the server never reads inside the payload.


-- ===========================================================================
-- clubs
-- ===========================================================================
-- One row per club using this backend. Everything else in the database hangs
-- off a club_id, so a query that forgets to filter by club is a tenancy bug.
--
-- secret_hash is the SHA-256 (hex) of the club's shared secret. The tablet
-- sends the secret, the Worker hashes what it receives and compares. Storing
-- the hash rather than the secret means a database dump does not hand someone
-- upload access.
--
-- Plain SHA-256 is only safe here because the secret is a long random string
-- generated by openssl, not a password someone chose. If you ever let a human
-- type their own club secret, this has to become PBKDF2 or scrypt, because a
-- human-chosen secret can be guessed from its hash and a random one cannot.
CREATE TABLE clubs (
  club_id        TEXT PRIMARY KEY,           -- short slug, e.g. 'njgc'
  display_name   TEXT NOT NULL DEFAULT '',
  secret_hash    TEXT NOT NULL,              -- hex SHA-256 of the shared secret
  secret_version INTEGER NOT NULL DEFAULT 1, -- bumped when the secret is rotated
  active         INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  created_at     INTEGER NOT NULL,           -- epoch milliseconds

  CHECK (length(club_id) BETWEEN 1 AND 64),
  CHECK (length(secret_hash) = 64)
);


-- ===========================================================================
-- club_admins
-- ===========================================================================
-- Used only by the human-facing management routes, which sit behind
-- Cloudflare Access. Access proves who the person is; this table decides which
-- club they are allowed to touch. Without it, any Access-authenticated user
-- could read any club's data.
--
-- Emails are stored in the clear because they are the lookup key. These are
-- club officers, not competitors.
CREATE TABLE club_admins (
  club_id    TEXT NOT NULL REFERENCES clubs(club_id) ON DELETE CASCADE,
  email      TEXT NOT NULL,                  -- lowercased before insert
  created_at INTEGER NOT NULL,

  PRIMARY KEY (club_id, email)
);

-- Supports "which clubs does this signed-in person belong to?"
CREATE INDEX idx_club_admins_email ON club_admins(email);


-- ===========================================================================
-- squad_uploads
-- ===========================================================================
-- One row per upload of one squad. Rows are never updated or deleted, only
-- added: each upload of the same squad gets the next revision number, and the
-- current data is whichever revision is highest.
--
-- Append-only costs a few extra rows and protects against the failure that
-- actually happens at a match: a tablet gets reopened, ends up holding partial
-- data, and re-uploads over a good result. With revisions the good one is
-- still there.
--
-- match_key and squad_key are normalized strings the tablet computes from
-- meta.match and meta.squad. The server treats them as opaque identifiers and
-- never parses them, so if the app later gains real match ids it can send
-- those instead without a schema change.
CREATE TABLE squad_uploads (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  club_id        TEXT NOT NULL REFERENCES clubs(club_id) ON DELETE CASCADE,

  -- Identity of this squad's data. match_type is part of the key because the
  -- app refuses to merge indoor and outdoor data, so an indoor and an outdoor
  -- match on the same date must not collide here either.
  match_key      TEXT NOT NULL,
  squad_key      TEXT NOT NULL,
  match_type     TEXT NOT NULL CHECK (match_type IN ('indoor', 'outdoor')),
  revision       INTEGER NOT NULL CHECK (revision >= 1),

  -- The labels as actually typed on the tablet. The keys above are normalized
  -- for matching; these are what a person should see in a list.
  match_label    TEXT NOT NULL DEFAULT '',
  squad_label    TEXT NOT NULL DEFAULT '',

  -- Which app produced this. When a payload turns out to be wrong, this is how
  -- you find out which tablet and which build to go look at.
  schema_version INTEGER NOT NULL,
  app_version    TEXT NOT NULL DEFAULT '',
  app_build      TEXT NOT NULL DEFAULT '',

  -- Number of entries in the payload, so the list endpoint can show
  -- "Squad 3 — 8 shooters" without opening the payload.
  entry_count    INTEGER NOT NULL DEFAULT 0,

  -- SHA-256 (hex) of the payload text. If a tablet re-sends data it already
  -- sent, the hash matches and the Worker returns the existing revision rather
  -- than creating a duplicate. This is the same idea as the app's
  -- scoreFingerprint check during merge.
  content_hash   TEXT NOT NULL,
  payload        TEXT NOT NULL,              -- the app's JSON, verbatim

  uploaded_at    INTEGER NOT NULL,           -- epoch ms, set by the server

  -- Set once a roster revision has taken in this squad's shooters. Until then,
  -- any shooter added at check-in on this tablet exists in this row and
  -- nowhere else, so this answers "is there anything nobody has compiled yet?"
  merged_into_roster_revision INTEGER,

  UNIQUE (club_id, match_key, squad_key, revision),
  CHECK (length(squad_key) > 0),
  CHECK (length(content_hash) = 64)
);

-- Main read path: the newest revision of one squad.
CREATE INDEX idx_squad_lookup
  ON squad_uploads (club_id, match_key, squad_key, revision DESC);

-- Listing what has been uploaded for a match.
CREATE INDEX idx_squad_match_list
  ON squad_uploads (club_id, match_key, uploaded_at DESC);

-- The duplicate check described above.
CREATE INDEX idx_squad_content_hash
  ON squad_uploads (club_id, match_key, squad_key, content_hash);

-- Finding squads not yet folded into a roster.
CREATE INDEX idx_squad_unmerged
  ON squad_uploads (club_id, merged_into_roster_revision);


-- ===========================================================================
-- rosters
-- ===========================================================================
-- The club's shooter list. Same JSON shape as a squad payload, because the app
-- builds a roster by exporting a normal payload with the scores cleared.
--
-- Unlike squads, this is multi-writer: any tablet can compile and push a new
-- roster. So writes are conditional. The client sends the revision it compiled
-- from as base_revision, and the Worker rejects the write if the current
-- revision has moved on since then. Without that check, two people compiling
-- at the same time means one of them silently loses every shooter the other
-- added — and this is the only data here that cannot be reconstructed from
-- somewhere else.
CREATE TABLE rosters (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  club_id        TEXT NOT NULL REFERENCES clubs(club_id) ON DELETE CASCADE,
  revision       INTEGER NOT NULL CHECK (revision >= 1),

  content_hash   TEXT NOT NULL,              -- hex SHA-256 of payload
  payload        TEXT NOT NULL,              -- the app's JSON, verbatim
  entry_count    INTEGER NOT NULL DEFAULT 0,

  schema_version INTEGER NOT NULL,
  app_version    TEXT NOT NULL DEFAULT '',
  app_build      TEXT NOT NULL DEFAULT '',

  -- The revision this one was compiled from. Used for the conflict check, and
  -- it leaves a readable trail of how the roster grew.
  base_revision  INTEGER,

  -- Who pushed it: a tablet label, or the Access email for a management write.
  -- Present so a rejected write can say who got there first instead of just
  -- reporting a conflict.
  author         TEXT NOT NULL DEFAULT '',

  updated_at     INTEGER NOT NULL,           -- epoch ms, set by the server

  UNIQUE (club_id, revision),
  CHECK (length(content_hash) = 64)
);

CREATE INDEX idx_roster_latest ON rosters (club_id, revision DESC);